### ISSUE TITLE
Great Share. But I can't find audio_reader ?

### ISSUE THREAD

**Issue by b21791675** [Aurora11111/speaker-recognition-pytorch#2]
Thanks for sharing this great project. When I tried to run project I got two different import error
 1) unresolved import 'audio_reader'
2)unresolved import 'constants'
Please can you inform how can I find these files ?

**Comment by jpmcarrilho** [comment]
I think this repo is Based on @philipperemy 'deep-speaker', There is an audio_reader.py file in in. I copied it to run the devector.py (hoping there is no conflict)  https://github.com/philipperemy/deep-speaker

**Comment by philipperemy** [comment]
Or here too: https://github.com/philipperemy/speaker-change-detection/blob/master/audio/audio_reader.py

**Comment by Aurora11111** [comment]
Yes,it's based on @philipperemy 'deep-speaker'.

**Comment by Aurora11111** [comment]
@b21791675  sorry I forget to upload the audio_reader.py 
you can also download from @philipperemy

**Comment by philipperemy** [comment]
@Aurora11111 can you close the issue if it's solved?
